# Generated by Django 4.2.9 on 2024-02-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
