# Generated by Django 4.2.9 on 2024-05-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
