# Generated by Django 4.2.9 on 2024-02-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_import_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('dev_level', models.CharField(max_length=100)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.role')),
                ('tech_stack', models.ManyToManyField(to='teams.technology')),
            ],
        ),
    ]
